
name: Build Media Journal WebApp
description: 'Build, test, and verify the web app and publish app package artifact.'

inputs:
  outputDirectory:
    description: 'The output directory for the dotnet publish command'
    required: true
  solutionRoot:
    description: 'The root directory of the solution'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Build Solution
      run: dotnet build --configuration Release
      shell: bash

    - name: Test Solution
      run: |
        dotnet test \
          --configuration Release \
          --no-build
      shell: bash

    - name: Publish Media Journal WebApp
      run: |
        dotnet publish \
          --configuration Release \
          --no-build \
          --output ${{ inputs.outputDirectory }} \
          ${{ inputs.solutionRoot }}/src/SlothParlor.MediaJournal.WebApp/
      shell: bash

    - name: Bundle EF Migrations
      run: | 
        dotnet ef migrations bundle -v \
          --configuration Release --no-build \
          --project ${{ inputs.solutionRoot }}/src/SlothParlor.MediaJournal.Data/ \
          --output ${{ inputs.outputDirectory }}/efbundle.exe \
          -- --no-connect 
      shell: bash
    
    - name: Upload App Artifact(s)
      uses: actions/upload-artifact@v4
      with:
        name: mj-webapp
        path: ${{ inputs.outputDirectory }}

    - name: Upload IaC Declarations (as Pipeline Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: mj-webapp-infrastructure
        path: ./infrastructure/azure