
name: Build Media Journal WebApp
description: 'Build, test, and verify the web app and publish app package artifact.'

inputs:
  outputDirectory:
    description: 'The output directory for the dotnet publish command'
    required: true
  dataProject:
    description: 'Path to the EFCore project'
    required: true
  webAppProject:
    description: 'Path to the startup project'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Build Solution
      run: dotnet build --configuration Release
      shell: bash

    - name: Ensure All Model Changes Have Migrations
      run: | 
        dotnet ef migrations has-pending-model-changes \
          --configuration Release --no-build \
          --project ${{ inputs.dataProject }} \
          --startup-project ${{ inputs.webAppProject }}
      shell: bash

    - name: Publish Media Journal WebApp
      run: |
        dotnet publish \
          --configuration Release 
          --project ${{ inputs.webAppProject }} \
          --output ${{ inputs.outputDirectory }}
      shell: bash

    - name: Bundle EF Migrations
      run: | 
        dotnet ef migrations bundle \
          --configuration Release --no-build \
          --project ${{ inputs.dataProject }} \
          --startup-project ${{ inputs.webAppProject }} \
          --output ${{ inputs.outputDirectory }}/migrationBundle.exe
      shell: bash
    
    - name: Upload App Artifact(s)
      uses: actions/upload-artifact@v4
      with:
        name: mj-webapp
        path: ${{ inputs.outputDirectory }}

    - name: Upload IaC Declarations (as Pipeline Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: mj-webapp-infrastructure
        path: ./infrastructure/azure