name: Media Journal CI/CD

on:
  push:
    branches:
      - main
    
jobs:

  build:
    name: Build, verify, and publish artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - uses: ./.github/actions/build-webapp

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/mj-webapp

      - name: Upload app artifact(s)
        uses: actions/upload-artifact@v3
        with:
          name: mj-webapp
          path: ${{env.DOTNET_ROOT}}/mj-webapp

      - name: Upload infrastructure declarations as artifact
        uses: actions/upload-artifact@v3
        with:
          name: infra
          path: ./infrastructure/azure

  deploy_infra_staging:
    name: "Update Infrastructure in Staging"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: 
      - build
    environment:
      name: 'Staging'
    outputs:
      webAppName: ${{ steps.deploy-infrastructure.outputs.webAppName }}
      appSubnetId: ${{ steps.deploy-infrastructure.outputs.appSubnetId }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download infrastructure artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: infra

      - name: Deploy Bicep file
        id: deploy-infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.TARGET_RESOURCE_GROUP }}
          template: main.incremental.bicep
          parameters: >-
            envName=staging
            appNamePrefix=sp-mj
            vnetResourceGroupName=${{ vars.VNET_RESOURCE_GROUP }}
            vnetName=${{ vars.VNET_NAME }}
            subnetName=${{ vars.SUBNET_NAME }}
          failOnStdErr: false

  deploy_app_staging:
    name: "Deploy Application to Staging"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: 
      - deploy_infra_staging
    environment:
      name: 'Staging'
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mj-webapp

      - name: Deploy to Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          resource-group-name: '${{ vars.TARGET_RESOURCE_GROUP }}'
          app-name: ${{ needs.deploy_infra_staging.outputs.webAppName }}
          # Note: Free/basic tiers only support "production" slot deployment, 
          # so the env var does value does not necessarily match the GitHub Actions Env name
          slot-name: '${{ vars.APP_SERVICES_DEPLOYMENT_SLOT }}' 
          package: .

      
