name: Build and Verify Media Journal Features 

on:
  pull_request:
    branches:
      - feature/*

jobs:
  # @todo: Add infrastructure verification

  integrate:
    # @todo: Add unit tests
    name: Integrate (Build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - uses: ./.github/actions/build-media-journal
        with:
          solutionRoot: ${{ github.workspace }}
          outputDirectory: ${{ env.DOTNET_ROOT }}/mj-webapp
