name: Test Azure Login with OpenID Connect and PowerShell

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'GitHub Actions environment used to contextualize the az login'
        type: choice
        required: true
        options:
          - 'Dev'
          - 'Staging'
        default: 'Staging'

permissions:
  id-token: write
  contents: read
      
jobs: 
  test-login:
    name: Test Azure Login with OpenID Connect and PowerShell
    runs-on: windows-latest

    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Login via OpenID Connect
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: 'Get Azure context'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext | ConvertTo-Json
          azPSVersion: "latest"